<definitions
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:rd="http://realdolmen.com/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        targetNamespace="http://realdolmen.com/"
        name="CarStatisticsService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://realdolmen.com/" schemaLocation="schema.xsd"/>
        </xsd:schema>
    </types>

    <message name="updateCarStatisticsRequest">
        <part name="parameters" element="rd:updateCarStatistics"/>
    </message>

    <message name="updateCarStatisticsResponse">
        <part name="parameters" element="rd:updateCarStatisticsResponse"/>
    </message>

    <portType name="UpdateCarStatistics">
        <operation name="updateCarStatistics">
            <input message="rd:updateCarStatisticsRequest"/>
            <output message="rd:updateCarStatisticsResponse"/>
        </operation>
    </portType>

    <binding name="UpdateCarStatisticsBinding" type="rd:UpdateCarStatistics">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="updateCarStatistics">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="CarStatisticsService">
        <port name="UpdateCarStatisticsServicePort" binding="rd:UpdateCarStatisticsBinding">
            <soap:address location="http://localhost:8080/webservice-module/CarStatisticsService"/>
        </port>
    </service>
</definitions>